name: SDWEBUI

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      SDWEBUI:
        description: 'THIS IS A SDWEBUI！'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: SDWEBUI
        run: |
          wget "https://github.com/tickstep/aliyunpan/releases/download/v0.2.6/aliyunpan-v0.2.6-linux-amd64.zip"
          unzip -d ~/ aliyunpan-v0.2.6-linux-amd64.zip
          ~/aliyunpan-v0.2.6-linux-amd64/aliyunpan login -RefreshToken=${{ secrets.ALIYUN }}
          
          bash <(wget -qO- https://raw.githubusercontent.com/AMEISKISS/stable-diffusion-webui/master/webui.sh)
          zip -r stable-diffusion-webui-$(date +%Y%m%d).zip /home/$(whoami)/stable-diffusion-webui/
          
          ~/aliyunpan-v0.2.6-linux-amd64/aliyunpan u stable-diffusion-webui-$(date +%Y%m%d).zip /
